title: My Adventure with WSL2
author: Muhammed Hussaini
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is one stop place for my journey in the world of technologgy. You'll get full update about what am tinkering with 
  at the moment. Currently am obsess with Docker and WSL2 and all things related to linux OS. 

# social links
twitter_username: _nazeer24 # DO NOT include the @ character, or else the build will fail!
github_username:  muhammednazeer # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
